<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="0" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-11-06T11:00:34 ART" name="Suite" finished-at="2020-11-06T11:00:35 ART" duration-ms="1030">
    <groups>
    </groups>
    <test started-at="2020-11-06T11:00:34 ART" name="Test" finished-at="2020-11-06T11:00:35 ART" duration-ms="1030">
      <class name="Pruebas.Test_Laboratorio4_E2">
        <test-method is-config="true" signature="setUp()[pri:0, instance:Pruebas.Test_Laboratorio4_E2@ea6147e]" started-at="2020-11-06T11:00:24 ART" name="setUp" finished-at="2020-11-06T11:00:34 ART" duration-ms="10031" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="crearCuentaInvalida(java.lang.String, java.lang.String)[pri:0, instance:Pruebas.Test_Laboratorio4_E2@ea6147e]" started-at="2020-11-06T11:00:35 ART" name="crearCuentaInvalida" data-provider="Datos Crear Cuenta Invalida" finished-at="2020-11-06T11:00:35 ART" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 4]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 4
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:49)
at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:145)
at org.testng.internal.Parameters.handleParameters(Parameters.java:797)
at org.testng.internal.Parameters.handleParameters(Parameters.java:740)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:789)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 4
at Utilidades.DatosExcel.leerExcel(DatosExcel.java:30)
at Pruebas.Test_Laboratorio4_E2.obtenerDatosExcel(Test_Laboratorio4_E2.java:52)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:76)
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:45)
... 25 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- crearCuentaInvalida -->
        <test-method is-config="true" signature="cierre()[pri:0, instance:Pruebas.Test_Laboratorio4_E2@ea6147e]" started-at="2020-11-06T11:00:36 ART" name="cierre" finished-at="2020-11-06T11:00:36 ART" duration-ms="159" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cierre -->
      </class> <!-- Pruebas.Test_Laboratorio4_E2 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
